// Generated by CoffeeScript 1.10.0
(function() {
  var postcss, times;

  postcss = require('postcss');

  times = postcss.plugin('postcss-times', function() {
    return function(css) {
      var re;
      re = /(.+):times\((\d+)\)/g;
      return css.walkRules(function(rule) {
        rule.selector = rule.selector.replace(re, function(_, selector, count) {
          var i, j, ref, selectors;
          if (/^(?:\.|#|\[)/.test(selector)) {
            selectors = [];
            for (i = j = 0, ref = Number(count); 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
              selectors.push(selector);
            }
            return selectors.join('');
          } else {
            return selector;
          }
        });
        return rule;
      });
    };
  });

  module.exports = times;

}).call(this);
